from dataclasses import dataclass
from enum import Enum
from typing import List, Optional


@dataclass
class LLMCase:
    """
    A dataclass representing a test case for evaluating language model outputs.

    This class encapsulates the inputs, outputs, and context for a single test case,
    commonly used in metrics or evaluation frameworks for language models.

    Parameters
    ----------
    user_input : Optional[str], optional
        The input provided by the user. Default is `None`.
    actual_output : Optional[str], optional
        The output generated by the actual system. Default is `None`.
    expected_output : Optional[str], optional
        The expected output for the test case. Default is `None`.
    context : Optional[List[str]], optional
        A list of contextual information related to the test case. Default is `None`.
    retrieval_context : Optional[List[str]], optional
        A list of retrieved context documents or information. Default is `None`.

    Notes
    -----
    This class is designed as a dataclass for easy initialization and comparison
    of test cases. All parameters are optional and default to `None` if not provided.

    Examples
    --------
    >>> case = LLMCase(
    ...     user_input="What is the capital of France?",
    ...     actual_output="Paris",
    ...     expected_output="Paris",
    ...     context=["France", "Europe"],
    ...     retrieval_context=["Paris is the capital", "France's geography"]
    ... )
    >>> print(case.user_input)
    'What is the capital of France?'
    """

    user_input: Optional[str] = None
    actual_output: Optional[str] = None
    expected_output: Optional[str] = None
    context: Optional[List[str]] = None
    retrieval_context: Optional[List[str]] = None


class LLMCaseParams(Enum):
    USER_INPUT = "user_input"
    ACTUAL_OUTPUT = "actual_output"
    EXPECTED_OUTPUT = "expected_output"
    CONTEXT = "context"
    RETRIEVAL_CONTEXT = "retrieval_context"
