#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from abc import ABC, abstractmethod
from typing import Any, List, Dict

from diting_core.callbacks.manager import new_group
from diting_core.utilities.slug import camel_to_snake
from diting_core.utilities.validate import assert_fields_validity


class BaseGenerateRule(ABC):
    """
    Abstract base class for data generate-rule in diting.

    Attributes:
        required_input_fields (List[str]): The list of input fields required for the rule.
        required_output_fields (List[str]): The list of output fields expected from the rule.
    """

    required_output_fields: List[str] = []
    required_input_fields: List[str] = []

    async def apply(self, rule_input: Dict[str, Any], **kwargs: Any) -> Dict[str, Any]:
        """Applies the generation rule to the provided input data.

        This method manages the execution of the rule, including input validation,
        callback management, and error handling. It ensures that the required input
        fields are present and that the output fields are valid.

        Args:
            rule_input (Dict[str, Any]): The input data for the rule, which must contain
                the required fields specified in `required_input_fields`.
            **kwargs (Any): Additional keyword arguments that may include:
                - callbacks: A list of callback functions to be executed during the rule application.
                - verbose: A boolean indicating whether to enable verbose logging.

        Returns:
            Dict[str, Any]: The output data generated by applying the rule, which must
            contain the required fields specified in `required_output_fields`.

        Raises:
            Exception: If there is an error during the rule application or if the input
            or output validation fails.
        """
        from diting_core.callbacks.base import ChainType

        run_manager, grp_cb = await new_group(
            name=self.name,
            inputs={"rule_input": rule_input},
            callbacks=kwargs.pop("callbacks", None),
            verbose=kwargs.pop("verbose", False),
            chain_type=ChainType.GENERATE_RULE,
            required_input_fields=self.required_input_fields,
            required_output_fields=self.required_output_fields,
        )
        try:
            assert_fields_validity(self.name, rule_input, self.required_input_fields)
            rule_output = await self._apply(rule_input, callbacks=grp_cb, **kwargs)
            assert_fields_validity(self.name, rule_output, self.required_output_fields)
        except Exception as e:
            await run_manager.on_chain_error(e)
            raise e
        await run_manager.on_chain_end({"rule_output": rule_output})
        return rule_output

    @abstractmethod
    async def _apply(self, rule_input: Dict[str, Any], **kwargs: Any) -> Dict[str, Any]:
        raise NotImplementedError

    @property
    def name(self) -> str:
        return camel_to_snake(self.__class__.__name__)
