#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from typing import List, Any, Optional, Dict

from pydantic import BaseModel

from diting_core.cases.llm_case import LLMCase
from diting_core.synthesis.rules.base_rule import BaseGenerateRule
from diting_core.synthesis.rules.qa.rule import QAGenerateRule


class BaseCorpus(BaseModel):
    """
    Base class for representing a corpus for generating LLMCase.

    Attributes
    ----------
    context : List[str]
        List of background information involved in the corpus.
    scenario: Optional[str] = None
        The scenario within the corpus
    """

    context: List[str]
    scenario: Optional[str] = None


class Synthesizer:
    @staticmethod
    async def generate(
        rule: BaseGenerateRule, rule_input: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generates output based on the provided rule and input.

        Args:
            rule (BaseGenerateRule): The rule to apply for generation.
            rule_input (Dict[str, Any]): The input data for the rule.

        Returns:
            Dict[str, Any]: The output generated by applying the rule to the input.
        """
        rule_output = await rule.apply(rule_input)
        return rule_output

    @staticmethod
    async def generate_llm_case_from_corpus(corpus: BaseCorpus) -> LLMCase:
        """Generates an LLMCase from the provided corpus.

        This method uses the QAGenerateRule to process the corpus and
        generate an LLMCase instance.

        Args:
            corpus (BaseCorpus): The corpus containing context and scenario.

        Returns:
            LLMCase: The generated LLMCase instance based on the corpus.
        """
        rule = QAGenerateRule()
        gen_ret = await Synthesizer.generate(rule, corpus.model_dump())
        return LLMCase.model_validate(gen_ret)
